### ISSUE TITLE
russell feedback

### ISSUE THREAD

**Issue by russellsamora** [the-pudding/photo-quiz#3]
* intro: images flash in then fade out
* intro: barely scrollable 
* results: needs recirculation / footer
* year: birth always starts at 85 (might skew results)
* slider is jittery on first hover
* slider: feel like if someone clicks submit without sliding it should be like, are you sure? to frictionless to advance

**Comment by jadiehm** [comment]
- [X] intro: images flash in then fade out
- [X] intro: barely scrollable
- [X] results: needs recirculation / footer
- [X] year: birth always starts at 85 (might skew results)
- [X] slider is jittery on first hover
- [x] slider: feel like if someone clicks submit without sliding it should be like, are you sure? to frictionless to advance
